#!/bin/bash
make clean_arm
make arm && scp pi_tester_arm pi@192.168.1.103:/home/pi/pt_arm
rsync -avz public_html pi@192.168.1.103:/home/pi/pt_arm
ssh 192.168.1.103 -lpi -t 'sudo /bin/bash -c "cd /home/pi/pt_arm && /home/pi/pt_arm/pi_tester_arm"'
